@startuml
left to right direction

actor User

usecase GetCards
usecase StartSwipping
usecase Swipe
usecase OpenConversation
usecase ReadMessage
usecase SendMessage
' usecase Login
usecase CreateProfile
' usecase GetProfile
usecase EditProfile
' usecase DeleteProfile


User --> GetCards
User --> StartSwipping
User --> Swipe
User --> OpenConversation
User --> ReadMessage
User --> SendMessage
User --> CreateProfile
User --> EditProfile
' User --> DeleteProfile
' User --> GetProfile
' User --> Unmatch



@enduml