@startuml

state INITIAL
state SWIPING
state CONVERSATION
state PROFILE

' Que estados faltan?
' Como nos movemos entre SWIPING - CONVERSATION - PROFILE
' Back use case?

[*] --> INITIAL
INITIAL --> IN_APP
note on link
GetCards
end note
IN_APP --> SWIPING
note on link
StartSwiping
endnote
SWIPING --> SWIPING
note on link
Swipe
endnote

CONVERSATION --> CONVERSATION
note on link
SendMessage
ReadMessage
end note

PROFILE --> PROFILE
note on link
EditProfile
end note
IN_APP --> PROFILE
note on link
EditProfile
end note

CONVERSATION --> PROFILE
note on link
CreateProfile
end note

SWIPING --> CONVERSATION
note on link
OpenConversation
end note
CONVERSATION --> SWIPING
note on link
StartSwiping
end note

SWIPING --> IN_APP
note on link
Swipe
end note




@enduml